#INS is INS as generated by New_Code_MSA

#INS3 runs the loop again. It calculates the average RNS of regions active in an industry.
KPn <- Template
KPn[, 2:ncol(KPn)] <- sweep(Template[, 2:ncol(Template)], 1, RNS$RNS, `*`)
KPn <- apply(KPn[, 2:ncol(KPn)], 2, function(x) { if (sum(x>0)==0) return(0) else return(mean(x[x>0])) })
INS$INS3 <- KPn
INS$INS3 <- scale(INS$INS3)
INS2 <- INS
INS2 <- INS2[order(-INS$INS3),]

#INS4 runs the loop again. This time it multiplies RNS by regions' relative activtiy.
KPn <- Template2
KPn[, 2:ncol(KPn)] <- sweep(Template2[, 2:ncol(Template2)], 1, RNS$RNS, `*`)
KPn <- apply(KPn[, 2:ncol(KPn)], 2, function(x) { if (sum(x>0)==0) return(0) else return(mean(x[x>0])) })
INS$INS4 <- KPn
INS$INS4 <- scale(INS$INS4)
INS2 <- INS
INS2 <- INS2[order(-INS$INS4),]

#INS5 runs the loop again. This time it multiplies RNS by each industry's proportion of a region's activity.
Calc3 <- Data
Calc3 <- Calc3 %>% left_join(DataRegionTotal, by=c("Region"="Region"))

Calc3$PA <- (Calc3$Quantity/Calc3$RegionTotal)
Calc3$Quantity <- Calc3$RegionTotal <- NULL
Template3 <- spread(Calc3, Industry, PA, fill = 0)

KPn <- Template3
KPn[, 2:ncol(KPn)] <- sweep(Template3[, 2:ncol(Template3)], 1, RNS$RNS, `*`)
KPn <- apply(KPn[, 2:ncol(KPn)], 2, function(x) { if (sum(x>0)==0) return(0) else return(mean(x[x>0])) })
INS$INS5 <- KPn
INS$INS5 <- scale(INS$INS5)
INS2 <- INS
INS2 <- INS2[order(-INS$INS5),]

#INS6 is similar to INS5, but it uses the sum of RNSes rather than the mean

KPn <- Template3
KPn[, 2:ncol(KPn)] <- sweep(Template3[, 2:ncol(Template3)], 1, RNS$RNS, `*`)
KPn <- apply(KPn[, 2:ncol(KPn)], 2, function(x) { if (sum(x>0)==0) return(0) else return(sum(x[x>0])) })
INS$INS6 <- KPn
INS$INS6 <- scale(INS$INS6)
INS2 <- INS
INS2 <- INS2[order(-INS$INS6),]
